language: node_js
node_js:
 - "node"
env:
- MY_VAR=EverythignIsAwesome
- NODE_ENV=TEST


addons:
  sonarcloud:
  Organization: "manibabum-github" 
  secure: "38e2c6ff14510f886cff64ee04018243bbae3118"

 
script:
 
  - sonar-scanner
  - sonar-scanner -Dsonar.login=38e2c6ff14510f886cff64ee04018243bbae3118


deploy:
  provider: azure_web_apps
  username: manibabu.muddapu01@gmail.com       # If AZURE_WA_USERNAME isn't set
  password: manemagee@1   # If AZURE_WA_PASSWORD isn't set
  site: https://manibabu.azurewebsites.net       # If AZURE_WA_SITE isn't set
  slot: azure_deployment_slotname       # (optional) If AZURE_WA_SLOT isn't set
